name: CI devops 2025

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04 # Version plus récente que 'ubuntu-latest'

    steps:
    - name: Checkout your github code using actions/checkout@v4
      uses: actions/checkout@v4

   # ... (votre code existant)

    # Étape 2: Configurer l'environnement Java
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' 
        distribution: 'temurin'
        # MODIFICATION : Utilisation du chemin simple-api

    # Étape 3: Construire le projet et exécuter les tests
    - name: Build with Maven and run tests
      # MODIFICATION : Utilisation de l'option -f avec le chemin simple-api
      run: mvn clean verify -f BackendAPI/pom.xml
